baseurl = "https://shirhatti.com/"
languageCode = "en-us"
title = "Shirhatti"
disqusShortname = "shirhatti"
paginate = 10
theme = "hyde-x"

[author]
    name = "Sourabh Shirhatti"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[taxonomies]
    category = "categories"

[params]
    # Sidebar social links.
    github = "https://github.com/shirhatti"
    twitter = "https://twitter.com/sshirhatti"
    mastodon = "https://hachyderm.io/@shirhatti"
    highlight = "solarized_light"

    tagline = "PM @ Uber<br />[UT Austin](https://www.utexas.edu/) Alumnus<br />Bengaluru native"

    googleAnalytics = "UA-73348939-1"

    gravatarHash = "010f20d07201bcb144d45f288276ec72"
